### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by yachaka** [cferdinandi/smooth-scroll#418]
Server-side rendering doesn't work because `smooth-scroll` expects `document` to be defined.

**Temporary workaround :**

In webpack plugins, use
```js
new webpack.NormalModuleReplacementPlugin(/smooth-scroll/, './myMock.js')
```
for your server-side configuration.

**Comment by yachaka** [comment]
Yes, but atm you can't bundle it if you're using server-side rendering as it will throw when trying to render it server-side.
So the state of the package doesn't allow it to be used in a isomorphic application.

**Comment by cferdinandi** [comment]
I haven't used an isomorphic JS framework so forgive me for my ignorance, but the problem *shouldn't* manifest until you instantiate the plugin, right? And that should only happen in the client.

**Comment by yachaka** [comment]
The problem happens https://github.com/cferdinandi/smooth-scroll/blob/master/src/js/smooth-scroll.js#L20

This is executed at module instantiation, and in a server-side environment `document` is undefined
`ReferenceError: document is not defined` is thrown when building with webpack

**Comment by yachaka** [comment]
Fixed in #419

**Comment by cferdinandi** [comment]
The thing that's still not clear to me... instantiation should only happen in the client, not on the server.

The fix you submitted isn't necessary unless you're instantiating on the server, which you shouldn't be. Is there a way to not do that?

**Comment by yachaka** [comment]
I'm not instantiating the plugin on the server, I'm requiring the module on the server, because I need to produce an HTML string of my react app to send it to the client.

What I'm doing on the server is :

```
import MyReactApp from './MyReactApp'

const html = ReactDOMServer.renderToString(<MyReactApp />)
res.send(html)
```

But `MyReactApp` is requiring `smooth-scroll`. So the module is imported server-side.
And at the moment, the `document` check is executed when the module is required, not when the `SmoothScroll` class is instantiated (which only happens on the client, because it is instantiated in the `componentDidMount` lifecycle callback).

So my PR aims to solve that by moving the `document` check to be executed at `SmoothScroll` class instantiation rather than at module import

**Comment by yachaka** [comment]
The primary goal of server-side rendering is to produce HTML for your app to be crawled by search engines, so you have to import your app on the server

**Comment by cferdinandi** [comment]
Sorry for the delay here. Just released version 14, and moved the feature test to a function (per your recommendation), fixing this issue. Cheers!
